#!/bin/bash

echo "=================== Cdisk ====================="
echo "=== Penggunaan Ruang Disk (Partisi Penting) ==="
echo ""
df -h / /home /var

echo ""

echo "========= Ukuran Direktori Home Anda =========="
du -sh /home /$USER 2>/dev/null

echo "==============================================="
echo "Selesai Cek Disk."
